name: CI Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      # - name: Start MongoDB
      #   uses: supercharge/mongodb-github-action@1.9.0
      #   with:
      #     mongodb-version: '6.0'

      - name: Install Dependencies
        run: npm install

      - name: Run Standard Style Check
        run: npx standard

      - name: Build
        run: npm run build --if-present

      - name: Debug Secrets
        run: |
          echo "My first secret: ${{ secrets.API_KEY }}"
          echo "My second secret: ${{ secrets.PROJECT_ID }}"

      - name: Run Tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
        run: npm test
      #   run: npm run test-ci # need to set up test-ci in package.json
